apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hush-k8s-goat-app.fullname" . }}
  labels:
    {{- include "hush-k8s-goat-app.labels" . | nindent 4 }}
type: Opaque
data:
  hubspot-api-key: {{ .Values.credentials.hubspotApiKey | b64enc | quote }}
